const Menu = [
  {
    id: 1,
    image: "images/pic1.jpeg",
    name: "Palm harbor",
    p: "Lorem",
    category: "rent",
    price: "$2,095",
    description: "2699 Green Valley,Highland Lake",
  },
  {
    id: 2,
    image: "images/pic2.jpg",
    name: "Beverly Springfield",
    p: "Lorem",
    category: "sell",
    price: "$2,700",
    description: "2821 Lane,Palm Harbor",
  },
  {
    id: 3,
    image: "images/pic3.jpg",
    name: "Faulkner Ave",
    p: "Lorem",
    category: "rent",
    price: "$4,500",
    description: "909 Woodland St Michigen IN",
  },
  {
    id: 4,
    image: "images/pic4.jpg",
    name: "AmitiVille",
    p: "Lorem",
    category: "buy",
    price: "$2,500",
    description: "101 pinkcity",
  },
  {
    id: 5,
    image: "images/pic5.jpg",
    name: "Barn Gate 19",
    p: "Lorem",
    category: "rent",
    price: "$2,175",
    description: "908 sandland pink villa",
  },
  {
    id: 6,
    image: "images/pic6.jpg",
    name: "Four Gables",
    p: "Lorem",
    category: "rent",
    price: "$2,175",
    description: "786 near woodlans park",
  },
  {
    id: 7,
    image: "images/pic7.webp",
    name: "Cherry Croft",
    p: "Lorem",
    category: "rent",
    price: "$2,175",
    description: "1190 park evenue",
  },
  {
    id: 8,
    image: "images/pic8.webp",
    name: "The Haven",
    p: "Lorem",
    category: "Buy",
    price: "$2,175",
    description: "1167 Krishna Cottage",
  },
  {
    id: 9,
    image: "images/pic9.jpg",
    name: "The Cottage",
    p: "Lorem",
    category: "Buy",
    price: "$2,175",
    description: "1213 shaam cottage",
  },
  {
    id: 10,
    image: "images/pic10.jpg",
    name: "Ivy Cottage",
    p: "Lorem",
    category: "Sell",
    price: "$2,175",
    description: "1357 Stephen Cottage",
  },
  {
    id: 11,
    image: "images/pic11.jpg",
    name: "The Stables",
    p: "Lorem",
    category: "sell",
    price: "$2,175",
    description: "1345 st Merry IN",
  },
  {
    id: 12,
    image: "images/pic12.jpg",
    name: "Orchard Cottage",
    p: "Lorem",
    category: "rent",
    price: "$2,175",
    description: "9876 St Joseph",
  },
];

export default Menu;
